import { rewriteFormula } from './formula-rewrite';
import { scratchCompatHeader } from './scratch-compat';
import type {
  AxisFinal,
  BindDirective,
  Diagnostic,
  MapDirective,
  MaxDirective,
  ParsedProject,
  RawBlock,
  RegionVerdict,
  RepeatDirective,
  WorkgroupSizeDirective,
} from './types';

/**
 * Structural subset of `MaxDirective` that `renameIdentifiers` reads.
 * Defined as a local type to keep the function signature stable across
 * future field additions.
 */
export type MaxDirectiveLike = Pick<MaxDirective, 'name' | 'internalName' | 'value'>;

/**
 * Structural subset of `RepeatDirective` that `renameIdentifiers` reads.
 * Defined as a local type to keep the function signature stable across
 * future field additions.
 */
export type RepeatDirectiveLike = Pick<RepeatDirective, 'name' | 'internalName'>;

export interface EmitInput {
  regionVerdict: RegionVerdict;
  parsedProject: ParsedProject;
  runtimeState?: { listLengths: Record<string, number> };
  /**
   * Optional device workgroup limits. When provided, `clampWorkgroupSize`
   * clamps against these instead of the conservative defaults — this
   * matches the real WebGPU device's `maxComputeWorkgroupSizeX/Y/Z` and
   * `maxComputeInvocationsPerWorkgroup`. Tests can omit this field to
   * exercise the conservative default path.
   */
  workgroupLimits?: WorkgroupLimits;
}

export interface WorkgroupSize {
  x: number;
  y: number;
  z: number;
}

export interface WorkgroupLimits {
  maxComputeWorkgroupSizeX: number;
  maxComputeWorkgroupSizeY: number;
  maxComputeWorkgroupSizeZ: number;
  maxComputeInvocationsPerWorkgroup: number;
}

export interface DispatchPlan {
  /** Dispatch workgroup count along X (ceil of extent / workgroupSize.x). */
  x: string;
  /** Dispatch workgroup count along Y. */
  y: string;
  /** Dispatch workgroup count along Z. */
  z: string;
}

export interface IdentifierRenameResult {
  renameTable: Record<string, string>;
  /** Diagnostics for collisions on either `@map` names or `@bind` names. */
  diagnostics: Diagnostic[];
  /** Subset of renameTable covering only `@bind` names. */
  bindingRenames: Record<string, string>;
}

export interface EmitResult {
  wgsl: string;
  diagnostics: Diagnostic[];
  /**
   * Structured dispatch plan — single source of truth for the runtime
   * dispatcher. `// dispatchWorkgroups(...)` inside the emitted WGSL is
   * documentary; `__dispatch-kernel-sync` reads this and computes the
   * integer dispatch extent.
   */
  dispatchPlan: DispatchPlan;
  /** Resolved (post-clamp) workgroup size for this region. */
  workgroupSize: WorkgroupSize;
}

const DEFAULT_WORKGROUP_SIZE: WorkgroupSize = { x: 64, y: 1, z: 1 };
const DEFAULT_WORKGROUP_LIMITS: WorkgroupLimits = {
  maxComputeWorkgroupSizeX: 256,
  maxComputeWorkgroupSizeY: 256,
  maxComputeWorkgroupSizeZ: 64,
  maxComputeInvocationsPerWorkgroup: 256,
};

/** Reserved WGSL keywords + the kernel-parameter names we generate. */
const RESERVED_IDENTIFIERS: ReadonlySet<string> = new Set([
  // WGSL keywords (subset large enough to cover anything likely to
  // collide with a user `@map` or `@bind` name).
  'alias',
  'array',
  'asm',
  'bf16',
  'bool',
  'break',
  'builtin',
  'case',
  'compute',
  'const',
  'const_assert',
  'continue',
  'continuing',
  'default',
  'discard',
  'dispatch',
  'do',
  'else',
  'enable',
  'enum',
  'f16',
  'f32',
  'f64',
  'false',
  'fn',
  'for',
  'global_invocation_id',
  'handle',
  'i8',
  'i16',
  'i32',
  'i64',
  'if',
  'let',
  'local_invocation_id',
  'loop',
  'mat',
  'override',
  'premerge',
  'regardless',
  'requires',
  'return',
  'struct',
  'switch',
  'true',
  'typedef',
  'u8',
  'u16',
  'u32',
  'u64',
  'unless',
  'using',
  'var',
  'vec',
  'void',
  'while',
  'workgroup_id',
  // Kernel parameter names generated by the emitter. User `@map`/`@bind`
  // names that collide with these would silently overwrite the WGSL
  // declaration; we force a rename instead. The legacy `gid`/`lid`/
  // `wid` (short-form kernel parameter names) are no longer emitted —
  // the emitter always uses `__tw_gid`/`__tw_lid`/`__tw_wid`, so user
  // `@map gid <- 0` etc. survive verbatim.
  '__tw_gid',
  '__tw_lid',
  '__tw_wid',
]);

const KNOWN_FORMULA_FUNCTIONS: ReadonlySet<string> = new Set([
  'select',
  'min',
  'max',
  'clamp',
  'sin',
  'cos',
  'pow',
  'exp',
  'log',
  'floor',
  'ceil',
  'fract',
  'abs',
  'sqrt',
  'mix',
  'step',
  'f32',
  'i32',
  'u32',
  'scratch_div',
  'scratch_mod',
  'scratch_index_clamp',
  'scratch_list_read_f32',
  'scratch_list_read_i32',
  'scratch_list_read_u32',
  'scratch_list_write_f32',
  'scratch_list_write_u32',
  'scratch_bool',
]);

const BINARY_INPUTS: Readonly<Record<string, readonly [string, string]>> = {
  operator_add: ['NUM1', 'NUM2'],
  operator_subtract: ['NUM1', 'NUM2'],
  operator_multiply: ['NUM1', 'NUM2'],
  operator_divide: ['NUM1', 'NUM2'],
  operator_mod: ['NUM1', 'NUM2'],
  operator_gt: ['OPERAND1', 'OPERAND2'],
  operator_lt: ['OPERAND1', 'OPERAND2'],
  operator_equals: ['OPERAND1', 'OPERAND2'],
  operator_and: ['OPERAND1', 'OPERAND2'],
  operator_or: ['OPERAND1', 'OPERAND2'],
};

interface EmitterContext {
  regionId: string;
  blocks: Record<string, RawBlock>;
  bindings: BindDirective[];
  bindingNames: Map<string, string>;
  lengthNames: Map<string, string>;
  renameTable: Record<string, string>;
  /** Maps a binding directive name to its emitted WGSL symbol. */
  bindingRenameTable: Record<string, string>;
  mapNames: Set<string>;
  /** Names declared via `@bind` (case-preserving). */
  bindNames: Set<string>;
  sequentialNames: Set<string>;
  diagnostics: Diagnostic[];
  diagnosedBlocks: Set<string>;
  expressionStack: Set<string>;
}

export function clampWorkgroupSize(
  size: Readonly<WorkgroupSize>,
  limits: Readonly<WorkgroupLimits>,
): WorkgroupSize {
  const maxInvocations = positiveInteger(limits.maxComputeInvocationsPerWorkgroup);
  const x = clampDimension(size.x, limits.maxComputeWorkgroupSizeX, maxInvocations);
  const remainingAfterX = Math.max(1, Math.floor(maxInvocations / x));
  const y = clampDimension(size.y, limits.maxComputeWorkgroupSizeY, remainingAfterX);
  const remainingAfterY = Math.max(1, Math.floor(remainingAfterX / y));
  const z = clampDimension(size.z, limits.maxComputeWorkgroupSizeZ, remainingAfterY);
  return { x, y, z };
}

/**
 * Rename identifiers that collide with reserved keywords or other
 * declared names. We collapse `@map` names, `@bind` names, and the
 * emitter-internal parameter names into a single collision map so a
 * user `@bind` named `let` doesn't shadow the WGSL `let` keyword.
 *
 * The returned `bindingRenames` is the subset that covers `@bind`
 * names; the runtime bridge uses it to rewrite the `LIST` field of
 * `data_variable` blocks when they're emitted.
 */
export function renameIdentifiers(
  maps: readonly MapDirective[],
  bindings: readonly BindDirective[] = [],
  regionId = '',
  maxes: readonly MaxDirectiveLike[] = [],
  repeats: readonly RepeatDirectiveLike[] = [],
): IdentifierRenameResult {
  const renameTable: Record<string, string> = {};
  const bindingRenames: Record<string, string> = {};
  const diagnostics: Diagnostic[] = [];
  const occupied = new Set<string>();

  // Seed `occupied` with already-emitted parameter names. Without this
  // step a user `@map gid` would silently overwrite the kernel gid
  // parameter; renaming forces an explicit, observable conflict. We do
  // NOT pre-seed binding / map names here — adding them to `occupied`
  // before the rename loop would make every name look like a duplicate
  // of itself and force a rename.
  for (const reserved of ['__tw_gid', '__tw_lid', '__tw_wid']) {
    occupied.add(reserved);
  }

  // 1. @bind names first — these are referenced by `data_variable` blocks
  //    in the body, so a collision with a WGSL keyword must rename before
  //    the body is emitted.
  for (const binding of bindings) {
    if (!binding.name) continue;
    // §Phase E: quoted names (e.g. `@bind "my list"(0) rw f32`) carry an
    // `internalName` set by the parser. The surface name may contain
    // characters that are illegal in a WGSL identifier (spaces,
    // punctuation) so it must be aliased to `internalName` for every
    // formula rewrite — not just when it collides with a reserved
    // keyword. Register `name → internalName` and skip the
    // reserved-keyword collision check (which would not match anyway).
    if (binding.internalName) {
      renameTable[binding.name] = binding.internalName;
      bindingRenames[binding.name] = binding.internalName;
      occupied.add(binding.internalName);
      continue;
    }
    if (!RESERVED_IDENTIFIERS.has(binding.name)) continue;
    let salt = 0;
    let renamed = hashedIdentifier(binding.name, salt);
    while (occupied.has(renamed) || RESERVED_IDENTIFIERS.has(renamed)) {
      salt += 1;
      renamed = hashedIdentifier(binding.name, salt);
    }
    occupied.add(renamed);
    bindingRenames[binding.name] = renamed;
    renameTable[binding.name] = renamed;
    diagnostics.push({
      severity: 'warn',
      code: 'gpu.identifier_collision',
      message: `@bind name '${binding.name}' was renamed to '${renamed}' for WGSL emission`,
      regionId,
      blockId: binding.line ? binding.line.toString() : undefined,
    });
  }

  // 2. @map names — same collision logic.
  for (const map of maps) {
    if (!map.var) continue;
    // §Phase E: quoted map names carry `internalName`. Mirror the @bind
    // branch above so formula-side identifier references resolve to the
    // WGSL `let` binding name.
    if (map.internalName) {
      if (renameTable[map.var] === undefined) {
        renameTable[map.var] = map.internalName;
        occupied.add(map.internalName);
      }
      continue;
    }
    if (!RESERVED_IDENTIFIERS.has(map.var)) continue;
    if (renameTable[map.var] !== undefined) continue;
    let salt = 0;
    let renamed = hashedIdentifier(map.var, salt);
    while (occupied.has(renamed) || RESERVED_IDENTIFIERS.has(renamed)) {
      salt += 1;
      renamed = hashedIdentifier(map.var, salt);
    }
    occupied.add(renamed);
    renameTable[map.var] = renamed;
    diagnostics.push({
      severity: 'warn',
      code: 'gpu.identifier_collision',
      message: `@map var '${map.var}' was renamed to '${renamed}' for WGSL emission`,
      regionId,
      blockId: map.blockId,
      line: map.line,
    });
  }

  // 3. §Phase E+ — @max group names. A quoted `@max "my group"=N`
  //    carries `internalName`. Any `@repeat`/`@map` formula that
  //    references the surface name must be rewritten to `internalName`
  //    for WGSL. Unquoted group names that collide with WGSL keywords
  //    are renamed through the same collision loop as @map.
  for (const max of maxes) {
    if (!max.name) continue;
    if (max.internalName) {
      if (renameTable[max.name] === undefined) {
        renameTable[max.name] = max.internalName;
        occupied.add(max.internalName);
      }
      continue;
    }
    if (!RESERVED_IDENTIFIERS.has(max.name)) continue;
    if (renameTable[max.name] !== undefined) continue;
    let salt = 0;
    let renamed = hashedIdentifier(max.name, salt);
    while (occupied.has(renamed) || RESERVED_IDENTIFIERS.has(renamed)) {
      salt += 1;
      renamed = hashedIdentifier(max.name, salt);
    }
    occupied.add(renamed);
    renameTable[max.name] = renamed;
    diagnostics.push({
      severity: 'warn',
      code: 'gpu.identifier_collision',
      message: `@max name '${max.name}' was renamed to '${renamed}' for WGSL emission`,
      regionId,
    });
  }

  // 4. §Phase E+ — @repeat names. Same collision logic; quoted @repeat
  //    names (`@repeat "R0":global_x = ...`) carry `internalName` so the
  //    emitter can rewrite any `@map idx <- "R0"` reference to a valid
  //    WGSL identifier.
  for (const repeat of repeats) {
    if (!repeat.name) continue;
    if (repeat.internalName) {
      if (renameTable[repeat.name] === undefined) {
        renameTable[repeat.name] = repeat.internalName;
        occupied.add(repeat.internalName);
      }
      continue;
    }
    if (!RESERVED_IDENTIFIERS.has(repeat.name)) continue;
    if (renameTable[repeat.name] !== undefined) continue;
    let salt = 0;
    let renamed = hashedIdentifier(repeat.name, salt);
    while (occupied.has(renamed) || RESERVED_IDENTIFIERS.has(renamed)) {
      salt += 1;
      renamed = hashedIdentifier(repeat.name, salt);
    }
    occupied.add(renamed);
    renameTable[repeat.name] = renamed;
    diagnostics.push({
      severity: 'warn',
      code: 'gpu.identifier_collision',
      message: `@repeat name '${repeat.name}' was renamed to '${renamed}' for WGSL emission`,
      regionId,
    });
  }

  return { renameTable, diagnostics, bindingRenames };
}

export function emitRegion(input: EmitInput): EmitResult {
  const { regionVerdict } = input;
  const diagnostics: Diagnostic[] = [];
  const maps = regionVerdict.directives.filter((item): item is MapDirective => item.kind === 'map');
  const repeats = regionVerdict.directives.filter(
    (item): item is RepeatDirective => item.kind === 'repeat',
  );
  const bindings = regionVerdict.directives
    .filter((item): item is BindDirective => item.kind === 'bind')
    .slice()
    .sort((a, b) => a.slot - b.slot);
  const maxes = regionVerdict.directives.filter(
    (item): item is MaxDirective => item.kind === 'max',
  );
  const workgroupDirective = regionVerdict.directives.find(
    (item): item is WorkgroupSizeDirective => item.kind === 'workgroup_size',
  );
  const requestedWorkgroup = workgroupDirective
    ? { x: workgroupDirective.x, y: workgroupDirective.y, z: workgroupDirective.z }
    : DEFAULT_WORKGROUP_SIZE;
  const workgroupLimits = input.workgroupLimits ?? DEFAULT_WORKGROUP_LIMITS;
  const workgroupSize = clampWorkgroupSize(requestedWorkgroup, workgroupLimits);

  if (!sameWorkgroupSize(requestedWorkgroup, workgroupSize)) {
    diagnostics.push({
      severity: 'info',
      code: 'gpu.workgroup_size_clamped',
      message: `workgroup size (${requestedWorkgroup.x}, ${requestedWorkgroup.y}, ${requestedWorkgroup.z}) was clamped to (${workgroupSize.x}, ${workgroupSize.y}, ${workgroupSize.z})`,
      regionId: regionVerdict.regionId,
      blockId: regionVerdict.blockId,
    });
  }

  const renamed = renameIdentifiers(maps, bindings, regionVerdict.regionId, maxes, repeats);
  diagnostics.push(...renamed.diagnostics);
  const blocks = collectTargetBlocks(input.parsedProject, regionVerdict.spriteId);
  const bindingNames = createBindingNames(bindings);
  // Override binding rename to use the canonical hashed name when one
  // was assigned by `renameIdentifiers`.
  for (const [original, renamedName] of Object.entries(renamed.bindingRenames)) {
    bindingNames.set(original, renamedName);
  }
  const lengthNames = new Map<string, string>();
  for (const binding of bindings) {
    const storageName = bindingNames.get(binding.name) ?? binding.name;
    lengthNames.set(binding.name, safeIdentifier(`${storageName}_length`));
  }

  const sequentialRepeats = repeats.filter(
    (repeat) => (regionVerdict.axes[repeat.name]?.finalAxis ?? repeat.axis) === 'sequential',
  );
  const context: EmitterContext = {
    regionId: regionVerdict.regionId,
    blocks,
    bindings,
    bindingNames,
    lengthNames,
    renameTable: renamed.renameTable,
    bindingRenameTable: renamed.bindingRenames,
    mapNames: new Set(maps.map((map) => map.var)),
    bindNames: new Set(bindings.map((b) => b.name)),
    sequentialNames: new Set(sequentialRepeats.map((repeat) => repeat.name)),
    diagnostics,
    diagnosedBlocks: new Set(),
    expressionStack: new Set(),
  };

  const lines: string[] = [scratchCompatHeader(), '', emitUniforms(bindings, lengthNames), ''];
  for (const binding of bindings) lines.push(emitBinding(binding, bindingNames));
  if (bindings.length > 0) lines.push('');

  const dispatchPlan = computeDispatchPlan(repeats, regionVerdict, workgroupSize, {
    bindings,
    renameTable: renamed.renameTable,
    bindingRenameTable: renamed.bindingRenames,
    regionId: regionVerdict.regionId,
  });
  lines.push(`// ${formatDispatchPlan(dispatchPlan)}`);
  lines.push(
    `@compute @workgroup_size(${workgroupSize.x},${workgroupSize.y},${workgroupSize.z})`,
  );
  lines.push(`${mainSignature(regionVerdict.parallelAxes)} {`);

  const orderedMaps = orderMaps(maps, regionVerdict.cascade.topoOrder);
  for (const map of orderedMaps) {
    // §Phase E: quoted `@map` names use `internalName` as the WGSL
    // `let` binding. The collision-rename pass above (renamed.renameTable)
    // already records `var → internalName` for quoted names, so falling
    // through to `renameTable[map.var]` covers both quoted and reserved
    // keyword collisions.
    const emittedName = renamed.renameTable[map.var] ?? map.var;
    const formula = emitFormula(map.formula, map, context);
    lines.push(`  let ${emittedName}: f32 = ${formula};`);
  }

  const bodyStart = findBodyStart(blocks[regionVerdict.blockId], blocks, regionVerdict.blockId);
  const bodyLines = bodyStart ? emitStatementChain(bodyStart, context) : [];
  appendSequentialBody(lines, bodyLines, sequentialRepeats, context);
  lines.push('}');

  return {
    wgsl: lines.join('\n'),
    diagnostics,
    dispatchPlan,
    workgroupSize,
  };
}

function positiveInteger(value: number): number {
  if (!Number.isFinite(value)) return 1;
  return Math.max(1, Math.floor(value));
}

function clampDimension(value: number, deviceLimit: number, invocationLimit: number): number {
  return Math.min(positiveInteger(value), positiveInteger(deviceLimit), invocationLimit);
}

function sameWorkgroupSize(a: Readonly<WorkgroupSize>, b: Readonly<WorkgroupSize>): boolean {
  return a.x === b.x && a.y === b.y && a.z === b.z;
}

function hashedIdentifier(identifier: string, salt: number): string {
  let hash = 0x811c9dc5;
  const input = salt === 0 ? identifier : `${identifier}:${salt}`;
  for (let index = 0; index < input.length; index += 1) {
    hash ^= input.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
  }
  return `__tw_${(hash >>> 0).toString(16).padStart(8, '0')}`;
}

function safeIdentifier(identifier: string): string {
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(identifier) && !RESERVED_IDENTIFIERS.has(identifier)) {
    return identifier;
  }
  return hashedIdentifier(identifier, 0);
}

/**
 * Public version of `safeIdentifier` for use by adjacent modules (e.g.
 * `formula-rewrite.ts`) that need the same collision-aware identifier
 * derivation. Returns the surface name when it is a WGSL-safe
 * identifier and not a reserved keyword; otherwise returns the
 * FNV-1a-hashed form. Used as the fallback when `renameTable` doesn't
 * yet know about a binding (e.g. when formula-rewrite runs before
 * `renameIdentifiers`).
 */
export function safeIdentifierForBinding(identifier: string): string {
  return safeIdentifier(identifier);
}

function collectTargetBlocks(project: ParsedProject, spriteId: string): Record<string, RawBlock> {
  const preferred = project.targets.find((target) => target.id === spriteId);
  if (preferred) return preferred.blocks;
  const blocks: Record<string, RawBlock> = {};
  for (const target of project.targets) Object.assign(blocks, target.blocks);
  return blocks;
}

function createBindingNames(bindings: readonly BindDirective[]): Map<string, string> {
  const names = new Map<string, string>();
  const occupied = new Set<string>();
  for (const binding of bindings) {
    // Quoted names (§Phase E) bypass the safeIdentifier round-trip —
    // `internalName` is already a valid FNV-1a-hashed WGSL identifier,
    // and the host-side `name` (which may contain spaces or punctuation)
    // is not a valid WGSL identifier. The `internalName` is also unique
    // by construction (FNV-1a of a 32-bit salt), so we can register it
    // directly without a salt loop.
    if (binding.internalName) {
      names.set(binding.name, binding.internalName);
      occupied.add(binding.internalName);
      continue;
    }
    let name = safeIdentifier(binding.name);
    let salt = 0;
    while (occupied.has(name)) {
      salt += 1;
      name = hashedIdentifier(binding.name, salt);
    }
    occupied.add(name);
    names.set(binding.name, name);
  }
  return names;
}

/**
 * Emit the uniforms struct at `@group(1) @binding(0)` to free `@group(0)`
 * for user storage bindings. Storage bindings then occupy `@group(0)
 * @binding(0) .. N`, and the user is free to use slot 0.
 */
function emitUniforms(
  bindings: readonly BindDirective[],
  lengthNames: ReadonlyMap<string, string>,
): string {
  const fields = bindings.map((binding) => {
    const name = lengthNames.get(binding.name) ?? safeIdentifier(`${binding.name}_length`);
    return `  ${name}: u32,`;
  });
  if (fields.length === 0) fields.push('  __tw_padding: u32,');
  return `struct ScratchUniforms {\n${fields.join('\n')}\n};\n@group(1) @binding(0) var<uniform> u_scratch: ScratchUniforms;`;
}

function emitBinding(
  binding: BindDirective,
  bindingNames: ReadonlyMap<string, string>,
): string {
  const access = binding.readOnly ? 'read' : 'read_write';
  // `byte` is logically a host-side Uint8Array, but WGSL has no
  // host-shareable u8 storage type — we use array<u32> with one u32
  // per element and pack low-8-bits in M5 (`list-buffer-binding.ts`
  // `coerceToTypedArray` for `byte` dtype). Helpers
  // `scratch_list_read_u32` / `scratch_list_write_u32` keep host and
  // shader in sync.
  const elementType = binding.dtype === 'i32'
    ? 'i32'
    : binding.dtype === 'byte'
      ? 'u32'
      : 'f32';
  const name = bindingNames.get(binding.name) ?? binding.name;
  return `@group(0) @binding(${binding.slot}) var<storage, ${access}> ${name}: array<${elementType}>;`;
}

function mainSignature(parallelAxes: RegionVerdict['parallelAxes']): string {
  const axes = new Set(parallelAxes.map((item) => item.axis));
  // Kernel parameter names are `__tw_gid` / `__tw_lid` / `__tw_wid` so
  // user `@map` declarations can freely use `gid`/`lid`/`wid` without
  // colliding with the WGSL parameter.
  const params = ['@builtin(global_invocation_id) __tw_gid: vec3<u32>'];
  if (hasAxisPrefix(axes, 'local_')) {
    params.push('@builtin(local_invocation_id) __tw_lid: vec3<u32>');
  }
  if (hasAxisPrefix(axes, 'workgroup_')) {
    params.push('@builtin(workgroup_id) __tw_wid: vec3<u32>');
  }
  return `fn main(${params.join(', ')})`;
}

function hasAxisPrefix(axes: ReadonlySet<AxisFinal>, prefix: string): boolean {
  for (const axis of axes) {
    if (axis.startsWith(prefix)) return true;
  }
  return false;
}

function orderMaps(maps: readonly MapDirective[], topoOrder: readonly string[]): MapDirective[] {
  const byName = new Map(maps.map((map) => [map.var, map]));
  const ordered: MapDirective[] = [];
  const emitted = new Set<string>();
  for (const name of topoOrder) {
    const map = byName.get(name);
    if (!map || emitted.has(name)) continue;
    ordered.push(map);
    emitted.add(name);
  }
  for (const map of maps) {
    if (!emitted.has(map.var)) ordered.push(map);
  }
  return ordered;
}

function emitFormula(
  rawFormula: string,
  directive: MapDirective | RepeatDirective,
  context: EmitterContext,
): string {
  validateFormula(rawFormula, directive, context);
  // §Phase E+ — apply general-notation sugar before identifier rewrite
  // so the rewrite pass sees only scratch-compat primitives.
  const rewrite = rewriteFormula(rawFormula, {
    bindings: context.bindings,
    renameTable: context.renameTable,
    regionId: context.regionId,
    blockId: directive.blockId,
    line: directive.line,
  });
  if (rewrite.diagnostics.length > 0) context.diagnostics.push(...rewrite.diagnostics);
  let formula = renameFormulaIdentifiers(
    rewrite.formula,
    context.renameTable,
    context.bindingRenameTable,
  );
  if (formula.includes('//')) {
    formula = substituteBinaryOperator(formula, '//', (left, right) => `floor(${left} / ${right})`);
    context.diagnostics.push({
      severity: 'info',
      code: 'gpu.emitter_integer_division_substituted',
      message: `integer division in '${directiveFormulaName(directive)}' was emitted as floor(a / b)`,
      regionId: context.regionId,
      blockId: directive.blockId,
      line: directive.line,
    });
  }
  if (formula.includes('^')) {
    formula = substituteBinaryOperator(formula, '^', (left, right) => `exp(${left} * log(${right}))`);
    context.diagnostics.push({
      severity: 'warn',
      code: 'gpu.emitter_generic_pow_substituted',
      message: `generic exponentiation in '${directiveFormulaName(directive)}' was emitted with exp/log`,
      regionId: context.regionId,
      blockId: directive.blockId,
      line: directive.line,
    });
  }
  return castI32Calls(formula);
}

function directiveFormulaName(directive: MapDirective | RepeatDirective): string {
  return directive.kind === 'map' ? directive.var : directive.name;
}

/**
 * Validate a formula's syntax. We accept a permissive subset:
 *   - numeric literals (`0`, `1.5`, `-3`, `6.022e23`, `-0`)
 *   - identifiers (alphanumeric + underscore), but reject function-call
 *     syntax for unknown identifiers
 *   - operators: `+ - * / % ^ ( ) , . < > = <= >= == != && || //`
 *
 * Anything else is flagged with a `gpu.emitter_invalid_formula_token`
 * diagnostic so the user knows their DSL was malformed. Bare reserved
 * keywords (e.g. `@map let <- 0`) are caught upstream by the rename
 * pass; this validator catches function-call syntax of unknown names
 * (e.g. `@map x <- undeclared_fn(y)`).
 */
function validateFormula(
  formula: string,
  directive: MapDirective | RepeatDirective,
  context: EmitterContext,
): void {
  const invalid = new Set<string>();
  let offset = 0;
  while (offset < formula.length) {
    const remaining = formula.slice(offset);
    const whitespace = remaining.match(/^\s+/);
    if (whitespace) {
      offset += whitespace[0].length;
      continue;
    }
    const number = remaining.match(/^(?:(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)/);
    if (number) {
      offset += number[0].length;
      continue;
    }
    const identifier = remaining.match(/^[A-Za-z_][A-Za-z0-9_]*/);
    if (identifier) {
      const token = identifier[0];
      const after = formula.slice(offset + token.length);
      if (/^\s*\(/.test(after) && !KNOWN_FORMULA_FUNCTIONS.has(token)) {
        // Also flag obvious reserved keywords that ended up in a formula
        // because the rename pass couldn't surface them (rare — usually
        // we hit them there).
        if (RESERVED_IDENTIFIERS.has(token)) {
          invalid.add(token);
        } else {
          invalid.add(token);
        }
      }
      offset += token.length;
      continue;
    }
    const operator = remaining.match(/^(?:\/\/|<=|>=|==|!=|&&|\|\||[+\-*/%^<>=!(),.])/);
    if (operator) {
      offset += operator[0].length;
      continue;
    }
    invalid.add(remaining[0] ?? '');
    offset += 1;
  }

  for (const token of invalid) {
    context.diagnostics.push({
      severity: 'warn',
      code: 'gpu.emitter_invalid_formula_token',
      message: `formula '${directiveFormulaName(directive)}' contains unsupported token '${token}'`,
      regionId: context.regionId,
      blockId: directive.blockId,
      line: directive.line,
    });
  }
}

function renameFormulaIdentifiers(
  formula: string,
  renameTable: Readonly<Record<string, string>>,
  bindingRenames?: Readonly<Record<string, string>>,
): string {
  // Binding renames take priority over @map renames. Storage bindings
  // surface as `@bind <name>` declarations in the WGSL output, and any
  // formula that references the bound list — directly or transitively
  // via `data_itemoflist`'s `LIST` field — would otherwise be emitted
  // with the original (potentially reserved) WGSL keyword. Without
  // binding rewrite, `@bind let(0) rw f32` followed by a `@map idx <- 0`
  // that references `let` would emit `let <hashed>: array<f32>` as the
  // storage variable but the formula would still emit `let` verbatim,
  // shadowing the WGSL keyword inside the function body.
  //
  // §Phase E+ — also rewrite quoted-string references (`"my list"`)
  // whose content matches an entry in `renameTable`. This lets the
  // user reference a quoted @bind/@max/@repeat by its surface name in
  // formulas. Quoted references resolve to the same `internalName` /
  // hashed emit name as the unquoted form.
  const lookup = (key: string): string | undefined => {
    if (bindingRenames && bindingRenames[key] !== undefined) return bindingRenames[key];
    return renameTable[key];
  };
  let out = formula.replace(/[A-Za-z_][A-Za-z0-9_]*/g, (identifier) => lookup(identifier) ?? identifier);
  out = out.replace(/"((?:[^"\\]|\\.)*)"/g, (match, body: string) => {
    const renamed = lookup(body);
    if (!renamed) return match;
    return renamed;
  });
  return out;
}

function substituteBinaryOperator(
  formula: string,
  operator: '//' | '^',
  replacement: (left: string, right: string) => string,
): string {
  const operand =
    '(?:[A-Za-z_][A-Za-z0-9_]*(?:\\.[A-Za-z_][A-Za-z0-9_]*)*(?:\\([^()]*\\))?|(?:\\d+(?:\\.\\d*)?|\\.\\d+)(?:[eE][+-]?\\d+)?|\\([^()]*\\))';
  const escaped = operator === '//' ? '\\/\\/' : '\\^';
  const pattern = new RegExp(`(${operand})\\s*${escaped}\\s*(${operand})`);
  let output = formula;
  let match = pattern.exec(output);
  while (match && match[1] !== undefined && match[2] !== undefined) {
    output = `${output.slice(0, match.index)}${replacement(match[1], match[2])}${output.slice(match.index + match[0].length)}`;
    match = pattern.exec(output);
  }
  return output;
}

function castI32Calls(formula: string): string {
  const functionName = 'scratch_list_read_i32';
  let output = formula;
  let searchFrom = 0;
  while (searchFrom < output.length) {
    const start = output.indexOf(`${functionName}(`, searchFrom);
    if (start < 0) break;
    if (output.slice(Math.max(0, start - 4), start) === 'f32(') {
      searchFrom = start + functionName.length;
      continue;
    }
    const open = start + functionName.length;
    const close = findClosingParen(output, open);
    if (close < 0) break;
    const call = output.slice(start, close + 1);
    output = `${output.slice(0, start)}f32(${call})${output.slice(close + 1)}`;
    searchFrom = close + 6;
  }
  return output;
}

function findClosingParen(value: string, openIndex: number): number {
  let depth = 0;
  for (let index = openIndex; index < value.length; index += 1) {
    const char = value[index];
    if (char === '(') depth += 1;
    else if (char === ')') {
      depth -= 1;
      if (depth === 0) return index;
    }
  }
  return -1;
}

/**
 * Compute the dispatch workgroup counts as WGSL expressions. These
 * expressions are evaluated on the JS side too — the runtime dispatcher
 * uses them to size `dispatchWorkgroups(...)` after substituting
 * runtime list lengths. The textual form is emitted as a comment for
 * documentation; the structured `DispatchPlan` is the source of truth.
 *
 * For each surviving axis we emit `ceil(<formula> / <denominator>)`.
 * The denominator is the workgroup size along that axis (1 for axes
 * that don't run in parallel — those are demoted to a sequential for
 * loop in WGSL).
 */
function computeDispatchPlan(
  repeats: readonly RepeatDirective[],
  verdict: RegionVerdict,
  workgroupSize: Readonly<WorkgroupSize>,
  context: {
    bindings: readonly BindDirective[];
    renameTable: Readonly<Record<string, string>>;
    bindingRenameTable: Readonly<Record<string, string>>;
    regionId: string;
  } | null = null,
): DispatchPlan {
  const formulas: string[][] = [[], [], []];
  for (const repeat of repeats) {
    const axis = verdict.axes[repeat.name]?.finalAxis ?? repeat.axis;
    if (axis === 'sequential' || axis.startsWith('local_')) continue;
    const dimension = axis.endsWith('_y') ? 1 : axis.endsWith('_z') ? 2 : 0;
    const denominator = dimension === 0 ? workgroupSize.x : dimension === 1 ? workgroupSize.y : workgroupSize.z;
    // §Phase E+ — apply the same formula-rewrite and rename pass that
    // `emitFormula` applies so the dispatch comment reflects the
    // scratch-compat expansion of `len(name)`, `bool(x)`, and quoted
    // group names. Without this, `len(my_list)` in a `@repeat` formula
    // would survive in the dispatch plan but the WGSL body would
    // already use `u_scratch.my_list_length`, causing a textual drift.
    let expanded = repeat.formula;
    if (context) {
      const rewrite = rewriteFormula(repeat.formula, {
        bindings: context.bindings,
        renameTable: context.renameTable,
        regionId: context.regionId,
        blockId: repeat.blockId,
        line: repeat.line,
      });
      expanded = renameFormulaIdentifiers(
        rewrite.formula,
        context.renameTable,
        context.bindingRenameTable,
      );
    }
    const formula = axis.startsWith('workgroup_')
      ? expanded
      : `ceil(${expanded} / ${denominator})`;
    formulas[dimension]?.push(formula);
  }
  const dims: ['x' | 'y' | 'z', number][] = [
    ['x', 0],
    ['y', 1],
    ['z', 2],
  ];
  const out: DispatchPlan = { x: '1', y: '1', z: '1' };
  for (const [key, idx] of dims) {
    const values = formulas[idx] ?? [];
    if (values.length === 1) out[key] = values[0] ?? '1';
    else if (values.length > 1) out[key] = `max(${values.join(', ')})`;
  }
  return out;
}

function formatDispatchPlan(plan: DispatchPlan): string {
  return `dispatchWorkgroups(${plan.x}, ${plan.y}, ${plan.z})`;
}

function findBodyStart(
  regionBlock: RawBlock | undefined,
  blocks: Readonly<Record<string, RawBlock>>,
  regionBlockId: string,
): string | null {
  if (regionBlock) {
    const substack = blockReference(regionBlock.inputs['SUBSTACK'], blocks);
    if (substack) return substack;
  }
  for (const block of Object.values(blocks)) {
    if (block?.parent === regionBlockId) return block.id;
  }
  return null;
}

function appendSequentialBody(
  lines: string[],
  bodyLines: readonly string[],
  repeats: readonly RepeatDirective[],
  context: EmitterContext,
): void {
  if (repeats.length === 0) {
    for (const line of bodyLines) lines.push(`  ${line}`);
    return;
  }

  let depth = 1;
  for (const repeat of repeats) {
    const name = context.renameTable[repeat.name] ?? repeat.name;
    const formula = emitFormula(repeat.formula, repeat, context);
    const indent = '  '.repeat(depth);
    lines.push(
      `${indent}// for (let ${name}: u32 = 0; ${name} < ${formula}; ${name} = ${name} + 1) {`,
    );
    lines.push(
      `${indent}for (var ${name}: u32 = 0u; ${name} < u32(${formula}); ${name} = ${name} + 1u) {`,
    );
    depth += 1;
  }
  for (const line of bodyLines) lines.push(`${'  '.repeat(depth)}${line}`);
  for (let index = repeats.length - 1; index >= 0; index -= 1) {
    depth -= 1;
    lines.push(`${'  '.repeat(depth)}}`);
  }
}

function emitStatementChain(startId: string, context: EmitterContext): string[] {
  const lines: string[] = [];
  const visited = new Set<string>();
  let currentId: string | null = startId;
  while (currentId !== null && !visited.has(currentId)) {
    visited.add(currentId);
    const currentBlock: RawBlock | undefined = context.blocks[currentId];
    if (!currentBlock) break;
    lines.push(...emitStatement(currentBlock, context));
    currentId = currentBlock.next;
  }
  return lines;
}

function emitStatement(block: RawBlock, context: EmitterContext): string[] {
  if (block.opcode === 'data_setvariableto') return [];
  if (block.opcode === 'data_replaceitemoflist') {
    const statement = emitListWrite(block, context);
    return statement ? [statement] : [];
  }
  if (BINARY_INPUTS[block.opcode] || block.opcode === 'operator_not' || block.opcode === 'data_itemoflist') {
    return [`let __tw_expr_${shortHash(block.id)}: f32 = ${emitBlockExpression(block, context)};`];
  }
  diagnoseUnsupported(block, context);
  return [];
}

function emitBlockExpression(block: RawBlock, context: EmitterContext): string {
  if (context.expressionStack.has(block.id)) {
    diagnoseUnsupported(block, context);
    return '0.0';
  }
  context.expressionStack.add(block.id);
  const expression = emitBlockExpressionInner(block, context);
  context.expressionStack.delete(block.id);
  return expression;
}

function emitBlockExpressionInner(block: RawBlock, context: EmitterContext): string {
  const binaryInputs = BINARY_INPUTS[block.opcode];
  if (binaryInputs) {
    const left = emitInput(block.inputs[binaryInputs[0]], context);
    const right = emitInput(block.inputs[binaryInputs[1]], context);
    switch (block.opcode) {
      case 'operator_add':
        return `(${left} + ${right})`;
      case 'operator_subtract':
        return `(${left} - ${right})`;
      case 'operator_multiply':
        return `(${left} * ${right})`;
      case 'operator_divide':
        return `scratch_div(${left}, ${right})`;
      case 'operator_mod':
        return `scratch_mod(${left}, ${right})`;
      case 'operator_gt':
        return `select(0.0, 1.0, ${left} >= ${right})`;
      case 'operator_lt':
        return `select(0.0, 1.0, ${left} <= ${right})`;
      case 'operator_equals':
        return `select(0.0, 1.0, ${left} == ${right})`;
      case 'operator_and':
        return `select(0.0, 1.0, scratch_bool(${left}) * scratch_bool(${right}) != 0.0)`;
      case 'operator_or':
        return `select(0.0, 1.0, max(scratch_bool(${left}), scratch_bool(${right})) != 0.0)`;
      default:
        break;
    }
  }
  if (block.opcode === 'operator_not') {
    const operand = emitInput(block.inputs['OPERAND'], context);
    return `select(1.0, 0.0, scratch_bool(${operand}) != 0.0)`;
  }
  if (block.opcode === 'data_itemoflist') return emitListRead(block, context);
  if (isNumberReporter(block.opcode)) return emitNumberField(block);
  if (block.opcode === 'data_variable') {
    const variable = fieldName(block.fields['VARIABLE']);
    if (variable && context.mapNames.has(variable)) {
      const name = context.renameTable[variable] ?? variable;
      return context.sequentialNames.has(variable) ? `f32(${name})` : name;
    }
  }
  diagnoseUnsupported(block, context);
  return '0.0';
}

function emitInput(input: unknown, context: EmitterContext): string {
  const reference = blockReference(input, context.blocks);
  if (reference) {
    const block = context.blocks[reference];
    if (block) return emitBlockExpression(block, context);
  }
  const literal = inputLiteral(input, context.blocks);
  if (typeof literal === 'number') return formatF32(literal);
  if (typeof literal === 'string') {
    const numeric = Number(literal);
    if (literal.trim().length > 0 && !Number.isNaN(numeric)) return formatF32(numeric);
    const renamed = context.renameTable[literal];
    if (renamed) return renamed;
    if (context.mapNames.has(literal)) return literal;
  }
  return '0.0';
}

function blockReference(
  input: unknown,
  blocks: Readonly<Record<string, RawBlock>>,
): string | null {
  if (typeof input === 'string' && blocks[input]) return input;
  if (Array.isArray(input)) {
    for (const item of input.slice(1)) {
      const reference = blockReference(item, blocks);
      if (reference) return reference;
    }
    return null;
  }
  if (!input || typeof input !== 'object') return null;
  const value = input as Record<string, unknown>;
  for (const key of ['id', 'block', 'shadow']) {
    const candidate = value[key];
    if (typeof candidate === 'string' && blocks[candidate]) return candidate;
  }
  return blockReference(value['value'], blocks);
}

function inputLiteral(
  input: unknown,
  blocks: Readonly<Record<string, RawBlock>>,
): string | number | null {
  if (typeof input === 'number') return input;
  if (typeof input === 'string') return blocks[input] ? null : input;
  if (Array.isArray(input)) {
    for (let index = input.length - 1; index >= 0; index -= 1) {
      const literal = inputLiteral(input[index], blocks);
      if (literal !== null) return literal;
    }
    return null;
  }
  if (!input || typeof input !== 'object') return null;
  const value = input as Record<string, unknown>;
  for (const key of ['value', 'text']) {
    const literal = inputLiteral(value[key], blocks);
    if (literal !== null) return literal;
  }
  return null;
}

function emitListRead(block: RawBlock, context: EmitterContext): string {
  const binding = bindingForList(block, context);
  if (!binding) {
    diagnoseUnsupported(block, context);
    return 'scratch_div(0.0, 0.0)';
  }
  const index = emitInput(block.inputs['INDEX'], context);
  const storageName = context.bindingNames.get(binding.name) ?? binding.name;
  const lengthName = context.lengthNames.get(binding.name) ?? `${storageName}_length`;
  const checkedIndex = `scratch_index_clamp(${index}, u_scratch.${lengthName})`;
  if (binding.dtype === 'f32') {
    return `scratch_list_read_f32(&${storageName}, ${checkedIndex}, u_scratch.${lengthName})`;
  }
  if (binding.dtype === 'i32') {
    return `f32(scratch_list_read_i32(&${storageName}, ${checkedIndex}, u_scratch.${lengthName}))`;
  }
  if (binding.dtype === 'byte') {
    // Each host byte maps to one u32 in the storage buffer (low 8 bits
    // hold the value). Returning the u32 directly is convenient because
    // most callers want an integer; downstream arithmetic will coerce.
    return `f32(scratch_list_read_u32(&${storageName}, ${checkedIndex}, u_scratch.${lengthName}))`;
  }
  diagnoseUnsupported(block, context);
  return 'scratch_div(0.0, 0.0)';
}

function emitListWrite(block: RawBlock, context: EmitterContext): string | null {
  const binding = bindingForList(block, context);
  if (!binding || binding.readOnly) {
    diagnoseUnsupported(block, context);
    return null;
  }
  const index = emitInput(block.inputs['INDEX'], context);
  const value = emitInput(block.inputs['ITEM'], context);
  const storageName = context.bindingNames.get(binding.name) ?? binding.name;
  const lengthName = context.lengthNames.get(binding.name) ?? `${storageName}_length`;
  const checkedIndex = `scratch_index_clamp(${index}, u_scratch.${lengthName})`;
  if (binding.dtype === 'f32') {
    return `scratch_list_write_f32(&${storageName}, ${checkedIndex}, u_scratch.${lengthName}, ${value});`;
  }
  if (binding.dtype === 'i32') {
    return `scratch_list_write_i32(&${storageName}, ${checkedIndex}, u_scratch.${lengthName}, i32(${value}));`;
  }
  if (binding.dtype === 'byte') {
    return `scratch_list_write_u32(&${storageName}, ${checkedIndex}, u_scratch.${lengthName}, u32(${value}));`;
  }
  diagnoseUnsupported(block, context);
  return null;
}

function bindingForList(block: RawBlock, context: EmitterContext): BindDirective | undefined {
  const listName = fieldName(block.fields['LIST']);
  if (listName) {
    // Exact name match first; this is what the runtime bridge uses to
    // resolve a scratch-vm `data_itemoflist` field into a binding.
    const exact = context.bindings.find((binding) => binding.name === listName);
    if (exact) return exact;
  }
  return context.bindings.length === 1 ? context.bindings[0] : undefined;
}

function fieldName(field: unknown): string | null {
  if (typeof field === 'string') return field;
  if (Array.isArray(field)) {
    const first = field[0];
    return typeof first === 'string' ? first : null;
  }
  if (!field || typeof field !== 'object') return null;
  const value = field as Record<string, unknown>;
  // Prefer `id` first: scratch-vm stores variable references as
  // `{ id, name }`, and the runtime bridge keys bindings by their
  // canonical id (`__getListBuffer` looks up by lower-cased name on the
  // runtime side, but the in-emitter shape uses the id from
  // `fields.LIST.id`). Fall back to `name` for tests / hand-built
  // shapes that omit `id`.
  for (const key of ['value', 'id', 'name']) {
    if (typeof value[key] === 'string') return value[key] as string;
  }
  return null;
}

function isNumberReporter(opcode: string): boolean {
  return (
    opcode === 'math_number' ||
    opcode === 'math_integer' ||
    opcode === 'math_whole_number' ||
    opcode === 'math_positive_number' ||
    opcode === 'math_angle'
  );
}

function emitNumberField(block: RawBlock): string {
  const raw = fieldName(block.fields['NUM']);
  if (raw === null) return '0.0';
  const number = Number(raw);
  return Number.isNaN(number) ? '0.0' : formatF32(number);
}

function formatF32(value: number): string {
  if (Number.isNaN(value)) return 'scratch_div(0.0, 0.0)';
  if (value === Number.POSITIVE_INFINITY) return 'scratch_div(1.0, 0.0)';
  if (value === Number.NEGATIVE_INFINITY) return 'scratch_div(-1.0, 0.0)';
  if (Object.is(value, -0)) return '-0.0';
  return Number.isInteger(value) ? `${value}.0` : String(value);
}

function diagnoseUnsupported(block: RawBlock, context: EmitterContext): void {
  if (context.diagnosedBlocks.has(block.id)) return;
  context.diagnosedBlocks.add(block.id);
  context.diagnostics.push({
    severity: 'warn',
    code: 'gpu.emitter_unsupported_opcode',
    message: `opcode '${block.opcode}' is not supported by the WGSL emitter`,
    regionId: context.regionId,
    blockId: block.id,
  });
}

function shortHash(value: string): string {
  return hashedIdentifier(value, 0).slice(-8);
}
