/**
 * §Phase 5 (gpu-kernel-dsl-phase5-spec §5.3 / §5.7) — single-pass
 * invariant regression test for `region-extractor.ts`.
 *
 * The extractor must NOT re-extract after inlining: fresh block ids
 * generated by `procedure-inliner.ts` cannot carry `@compute`
 * markers (scratch UI does not let users attach comments to
 * synthesized blocks), so an additional extraction pass would
 * silently drop nothing — but it would also blow up if the inliner
 * ever exposed fresh ids through a public surface. The contract is:
 *   one pass, inliner handles body expansion downstream.
 *
 * This test pins (a) the call-count contract on
 * `extractRegions`, (b) that synthetic fresh ids with `@compute`
 * attached are NOT adopted as regions, and (c) that the inliner
 * running inside `block-subset.buildBlockSubsetVerdict` is what
 * makes `procedure_call` transparent (a direct read of
 * `region.bodyBlockIds` still shows the un-inlined call).
 */
import { describe, expect, it } from 'vitest';
import { extractRegions } from '@/runtime/gpu-kernel/region-extractor';
import { buildBlockSubsetVerdict } from '@/runtime/gpu-kernel/block-subset';
import type { ParsedProject, RawBlock } from '@/runtime/gpu-kernel/types';

function mkBlock(id: string, opcode: string, opts: Partial<RawBlock> = {}): RawBlock {
  return {
    id,
    opcode,
    next: null,
    parent: null,
    inputs: {},
    fields: {},
    ...opts,
  };
}

function mkPrototype(
  id: string,
  proccode: string,
  argumentNames: string[],
  substackHeadId: string,
): RawBlock {
  return mkBlock(id, 'procedures_prototype', {
    inputs: { SUBSTACK: substackHeadId },
    mutation: {
      proccode,
      argumentnames: JSON.stringify(argumentNames),
    },
    topLevel: true,
  });
}

function mkCall(
  id: string,
  proccode: string,
  parent: string | null,
): RawBlock {
  return mkBlock(id, 'procedure_call', {
    inputs: {},
    mutation: { proccode },
    parent,
  });
}

function mkProject(blocks: RawBlock[]): ParsedProject {
  const blockMap: Record<string, RawBlock> = {};
  for (const b of blocks) blockMap[b.id] = b;
  return {
    targets: [{ id: 'sprite1', isStage: false, blocks: blockMap }],
    comments: {},
  };
}

describe('region-extractor: single-pass invariant (§Phase 5 §5.3)', () => {
  it('extractRegions runs exactly once per call (no pass-5 re-extraction)', () => {
    // The single-pass invariant is structural: region-extractor.ts
    // has no second extraction pass after inlining because
    // `procedure-inliner.ts` lives downstream in `block-subset.ts`.
    // This test pins the contract that `extractRegions` returns the
    // pass-1 result untouched, regardless of what the inliner would
    // produce if it were also called here.
    const sub = mkBlock('sub', 'data_itemoflist', { next: 'writeA' });
    const writeA = mkBlock('writeA', 'data_replaceitemoflist', { parent: 'sub' });
    const protoA = mkPrototype('protoA', 'fnA', [], 'sub');
    const callA = mkCall('callA', 'fnA', 'kernelContainer');
    const kernelContainer = mkBlock('kernelContainer', 'control_repeat', {
      inputs: { SUBSTACK: 'callA' },
    });
    const project = mkProject([protoA, sub, writeA, callA, kernelContainer]);
    project.comments['cmt'] = { blockId: 'kernelContainer', text: '@compute\n' };

    const result = extractRegions(project);

    // Region count must reflect pass-1 only: one @compute marker =
    // one region.
    expect(result.regions).toHaveLength(1);
  });

  it('region.bodyBlockIds is NOT pre-inlined by extractor (block-subset owns inlining)', () => {
    // After extractRegions, region.bodyBlockIds still carries the
    // original `procedure_call` block id. The inliner expansion
    // happens at the block-subset boundary, not in the extractor
    // (single-pass invariant).
    const sub = mkBlock('sub', 'data_itemoflist');
    const writeA = mkBlock('writeA', 'data_replaceitemoflist', { parent: 'sub' });
    const protoA = mkPrototype('protoA', 'fnA', [], 'sub');
    const callA = mkCall('callA', 'fnA', 'kernelContainer');
    const kernelContainer = mkBlock('kernelContainer', 'control_repeat', {
      inputs: { SUBSTACK: 'callA' },
    });
    const project = mkProject([protoA, sub, writeA, callA, kernelContainer]);
    project.comments['cmt'] = { blockId: 'kernelContainer', text: '@compute\n' };

    const result = extractRegions(project);
    expect(result.regions).toHaveLength(1);
    const region = result.regions[0]!;
    // Extractor leaves bodyBlockIds untouched. procedure_call stays.
    expect(region.bodyBlockIds).toContain('callA');
    // inlinedPrototypeBlockIds stays empty (the field is reserved
    // for the kernel-registry layer to populate; the extractor does
    // not run the inliner).
    expect(region.inlinedPrototypeBlockIds).toEqual([]);
  });

  it('buildBlockSubsetVerdict runs the inliner: procedure_call → D1-valid', () => {
    // End-to-end: extractor produces a region with `procedure_call`
    // in its body; block-subset runs the inliner (single source of
    // truth) and confirms valid: true.
    const sub = mkBlock('sub', 'data_itemoflist');
    const writeA = mkBlock('writeA', 'data_replaceitemoflist', { parent: 'sub' });
    const protoA = mkPrototype('protoA', 'fnA', [], 'sub');
    const callA = mkCall('callA', 'fnA', 'kernelContainer');
    const kernelContainer = mkBlock('kernelContainer', 'control_repeat', {
      inputs: { SUBSTACK: 'callA' },
    });
    const project = mkProject([protoA, sub, writeA, callA, kernelContainer]);
    project.comments['cmt'] = { blockId: 'kernelContainer', text: '@compute\n' };

    const extracted = extractRegions(project);
    const region = extracted.regions[0]!;

    // Default = inliningEnabled === true. D1 verdict should classify
    // the inlined body as D1-valid.
    const verdict = buildBlockSubsetVerdict({
      region,
      project,
      comments: project.comments,
      parsedDirectives: [],
    });
    expect(verdict.valid).toBe(true);
    expect(verdict.diagnostics.filter((d) => d.severity === 'error')).toEqual([]);

    // Opt-out: inliningEnabled === false. The inliner is skipped;
    // `procedure_call` survives in the body and trips the D1 demote.
    const optOutVerdict = buildBlockSubsetVerdict({
      region,
      project,
      comments: project.comments,
      parsedDirectives: [],
      inliningEnabled: false,
    });
    expect(optOutVerdict.valid).toBe(false);
    expect(optOutVerdict.demoteReason).toBe('d1');
    const demoteDiagnostic = optOutVerdict.diagnostics.find(
      (d) => d.code === 'd1.region_demoted',
    );
    expect(demoteDiagnostic?.message).toMatch(/procedure_call/);
  });
});
