import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import JSZip from 'jszip';
import {
  parseProjectJsonFromArrayBuffer,
  toParsedProject,
} from '@/runtime/player';
import { extractRegions } from '@/runtime/gpu-kernel/region-extractor';

/**
 * Build a minimal sb3 archive in memory. The `project.json` is the only
 * file the gpu-kernel loader ever reads; everything else is irrelevant
 * for these tests.
 */
async function buildSb3(projectJson: unknown): Promise<ArrayBuffer> {
  const zip = new JSZip();
  zip.file('project.json', JSON.stringify(projectJson));
  zip.file('assets/placeholder.txt', 'noop');
  return await zip.generateAsync({ type: 'arraybuffer' });
}

/**
 * §Phase 1 (§15.1): regression tests for the SB3 loader's comments
 * merge. Before this commit, `parseProjectJsonFromArrayBuffer` only
 * read `json.comments` (root), so any project whose `@compute` comment
 * lived on a target (= the official Scratch editor layout, e.g.
 * `expo-fixture.sb3`) yielded zero regions. The contract we now pin:
 *
 *   - per-target comments are merged into the loader's output
 *   - root `json.comments` overrides per-target on duplicate ids
 *   - downstream `extractRegions` finds the region when the SB3
 *     originates from a fixture (real SB3 byte stream)
 */
describe('parseProjectJsonFromArrayBuffer + toParsedProject (§15.1 comments merge)', () => {
  it('merges per-target comments so extractRegions finds the @compute region', async () => {
    // Build a minimal sb3 with one target carrying a `@compute` comment
    // — exactly the shape `expo-fixture.sb3` produces via the official
    // Scratch editor.
    const buf = await buildSb3({
      targets: [
        {
          isStage: true,
          name: 'Stage',
          variables: {},
          lists: {},
          broadcasts: {},
          blocks: {},
          comments: {},
          costumes: [],
          sounds: [],
        },
        {
          isStage: false,
          name: 'Expo',
          variables: {},
          lists: {},
          broadcasts: {},
          blocks: {
            b_substk: {
              id: 'b_substk',
              opcode: 'data_setvariableto',
              inputs: {},
              fields: { VARIABLE: ['result', null] },
              next: null,
              parent: 'repeat0',
            },
            repeat0: {
              id: 'repeat0',
              opcode: 'control_repeat',
              inputs: {
                TIMES: [2, 'times0'],
                SUBSTACK: 'b_substk',
              },
              fields: {},
              next: null,
              parent: null,
            },
            times0: {
              id: 'times0',
              opcode: 'math_number',
              inputs: {},
              fields: { NUM: [10, null] },
              next: null,
              parent: 'repeat0',
              shadow: true,
            },
          },
          comments: {
            cmt_compute: {
              blockId: 'b_substk',
              x: 0,
              y: 0,
              width: 200,
              height: 100,
              minimized: false,
              text: '@compute\n@bind tmp0(0) ro f32\n',
            },
          },
          costumes: [],
          sounds: [],
        },
      ],
    });

    const shape = await parseProjectJsonFromArrayBuffer(buf);
    expect(shape).not.toBeNull();
    const parsed = toParsedProject(shape!);
    expect(Object.keys(parsed.comments)).toContain('cmt_compute');
    expect(parsed.comments['cmt_compute']?.text).toContain('@compute');

    const { regions } = extractRegions(parsed);
    expect(regions).toHaveLength(1);
    expect(regions[0]?.commentId).toBe('cmt_compute');
  });

  it('reads the real expo-fixture.sb3 and finds the @compute region (§15.1 acceptance)', async () => {
    // The fixture is generated by `npm run fixtures:setup`; pretest
    // guarantees it exists. We read the bytes directly from disk so the
    // test exercises the same byte stream `loadProjectFromArrayBuffer`
    // feeds the loader.
    const fixturePath = resolve(
      process.cwd(),
      'test/.test-fixtures/expo-fixture.sb3',
    );
    const buf = readFileSync(fixturePath);

    const shape = await parseProjectJsonFromArrayBuffer(buf);
    expect(shape).not.toBeNull();
    const parsed = toParsedProject(shape!);

    // The fixture carries 3 comments on the sprite target; the merged
    // comments map must include the @compute one with the right text.
    const cmtCompute = parsed.comments['cmt_compute'];
    expect(cmtCompute).toBeDefined();
    expect(cmtCompute?.text.trim().startsWith('@compute')).toBe(true);

    // And the region extractor must surface the @compute region.
    const { regions } = extractRegions(parsed);
    expect(regions.length).toBeGreaterThanOrEqual(1);
    expect(regions.some((r) => r.commentId === 'cmt_compute')).toBe(true);
  });

  it('keeps global_x axis for legacy expo-fixture.sb3 via bound list reference (§15.4)', async () => {
    // §Phase 3 §15.4 — the legacy fixture uses `len(aabb_w)` so D2's
    // formula-reference check (axis-analysis.ts) sees the bound list
    // name and keeps the axis parallel. Previously the formula was
    // `@repeat R0:global_x = aabb_w` which D2 demoted; the fixture
    // has since been updated to use the explicit `len()` sugar form.
    const fixturePath = resolve(
      process.cwd(),
      'test/.test-fixtures/expo-fixture.sb3',
    );
    const buf = readFileSync(fixturePath);

    const shape = await parseProjectJsonFromArrayBuffer(buf);
    expect(shape).not.toBeNull();
    const parsed = toParsedProject(shape!);
    const { regions } = extractRegions(parsed);
    expect(regions.length).toBeGreaterThanOrEqual(1);

    const { buildRegionVerdicts } = await import(
      '@/runtime/gpu-kernel/region-verdict-pipeline'
    );
    const { verdicts } = buildRegionVerdicts({ parsedProject: parsed, regions });
    const computeVerdict = verdicts.find((v) =>
      Object.values(v.axes).some((a) => a.requestedAxis === 'global_x'),
    );
    expect(computeVerdict, 'expected a region with global_x axis').toBeDefined();
    const r0 = computeVerdict!.axes['R0'];
    expect(r0?.finalAxis).toBe('global_x');
    expect(r0?.demoteReason).toBeUndefined();
    // No D2 demote warning emitted for the legacy fixture.
    const d2Diags = computeVerdict!.diagnostics.filter((d) => d.code === 'd2.axis_demoted');
    expect(d2Diags).toEqual([]);
  });

  it('falls back to root json.comments when per-target carries nothing', async () => {
    const buf = await buildSb3({
      targets: [
        {
          isStage: true,
          name: 'Stage',
          variables: {},
          lists: {},
          broadcasts: {},
          blocks: {},
          comments: {},
          costumes: [],
          sounds: [],
        },
        {
          isStage: false,
          name: 'Sprite',
          variables: {},
          lists: {},
          broadcasts: {},
          blocks: {
            b: {
              id: 'b',
              opcode: 'data_setvariableto',
              inputs: {},
              fields: { VARIABLE: ['x', null] },
              next: null,
              parent: null,
            },
          },
          comments: {},
          costumes: [],
          sounds: [],
        },
      ],
      comments: {
        cmt_root: {
          blockId: 'b',
          x: 0,
          y: 0,
          width: 100,
          height: 50,
          minimized: false,
          text: '@compute\n@bind tmp0(0) ro f32\n',
        },
      },
    });

    const shape = await parseProjectJsonFromArrayBuffer(buf);
    expect(shape).not.toBeNull();
    const parsed = toParsedProject(shape!);
    expect(parsed.comments['cmt_root']?.text).toContain('@compute');
  });

  it('lets root json.comments override per-target on duplicate id', async () => {
    // Both layers carry `cmt_dup`; the root value should win.
    const buf = await buildSb3({
      targets: [
        {
          isStage: true,
          name: 'Stage',
          variables: {},
          lists: {},
          broadcasts: {},
          blocks: {},
          comments: {},
          costumes: [],
          sounds: [],
        },
        {
          isStage: false,
          name: 'Sprite',
          variables: {},
          lists: {},
          broadcasts: {},
          blocks: {
            b: {
              id: 'b',
              opcode: 'data_setvariableto',
              inputs: {},
              fields: { VARIABLE: ['x', null] },
              next: null,
              parent: null,
            },
          },
          comments: {
            cmt_dup: {
              blockId: 'b',
              x: 0,
              y: 0,
              width: 100,
              height: 50,
              minimized: false,
              text: '// per-target value',
            },
          },
          costumes: [],
          sounds: [],
        },
      ],
      comments: {
        cmt_dup: {
          blockId: 'b',
          x: 0,
          y: 0,
          width: 100,
          height: 50,
          minimized: false,
          text: '// root value (must win)',
        },
      },
    });

    const shape = await parseProjectJsonFromArrayBuffer(buf);
    expect(shape).not.toBeNull();
    const parsed = toParsedProject(shape!);
    expect(parsed.comments['cmt_dup']?.text).toBe('// root value (must win)');
  });

  it('returns null for a buffer that is not a valid sb3', async () => {
    const garbage = new TextEncoder().encode('not a zip').buffer as ArrayBuffer;
    const shape = await parseProjectJsonFromArrayBuffer(garbage);
    expect(shape).toBeNull();
  });
});
