import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  existsSync,
  readdirSync,
  statSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { resolve, join } from 'node:path';
// The generator script is JavaScript without a companion .d.ts file;
// we follow the `test/scripts/gen-bench-sb3.test.ts` pattern
// (`@ts-expect-error` + relative import) so this test stays in lockstep
// with the script's exports without redeclaring them in a sidecar.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error -- ensure-test-fixtures.mjs is JS without a sidecar .d.ts
import * as EnsureFixtures from '../../scripts/ensure-test-fixtures.mjs';

/**
 * Re-export the typed surface from the namespace import so the rest of
 * the test file treats the symbols like real exports. The destructure
 * keeps call-site terse without re-running the `@ts-expect-error`
 * suppression on every reference.
 */
const {
  DEFAULT_FIXTURES,
  FIXTURE_GENERATORS,
  ensureTestFixtures,
  resolveRepoRoot,
} = EnsureFixtures as unknown as {
  DEFAULT_FIXTURES: readonly string[];
  FIXTURE_GENERATORS: Readonly<Record<string, () => Promise<unknown>>>;
  ensureTestFixtures: (options?: {
    cwd?: string;
    only?: string[];
  }) => Promise<{
    outDir: string;
    written: string[];
    skipped: string[];
  }>;
  resolveRepoRoot: (fromUrl?: string) => string;
};

/**
 * Unit tests for `scripts/ensure-test-fixtures.mjs`.
 *
 * Scope:
 *   - Registry wiring: every default fixture name has a real generator
 *     and the keys look like on-disk filenames (`.sb3`).
 *   - Idempotent overwrite: stomping a fixture with garbage and re-running
 *     produces a well-formed ZIP again. Uses the real `.test-fixtures/`
 *     (gitignored) so the fixtures themselves are byte-deterministic.
 *   - Filter contract: `only` restricts the set; unknown names are
 *     surfaced as `skipped` instead of throwing.
 *
 * Why not use a per-test sandbox: the generator scripts
 * (`scripts/gen-bench-sb3.mjs`, etc.) resolve their `outDir` at module
 * load from `__dirname/..` and capture it in module scope. Threading a
 * `cwd` override through each generator would require touching every
 * generator for one feature the production path doesn't need. Instead,
 * we test against the real `.test-fixtures/` — it is gitignored so
 * mutation is safe, and the generated bytes are deterministic so
 * post-state assertions are stable.
 */

const realRoot = resolveRepoRoot();
const realOutDir = resolve(realRoot, '.test-fixtures');

describe('ensure-test-fixtures: registry wiring', () => {
  it('every entry in DEFAULT_FIXTURES is backed by FIXTURE_GENERATORS', () => {
    for (const name of DEFAULT_FIXTURES) {
      expect(typeof FIXTURE_GENERATORS[name], `missing generator for ${name}`).toBe(
        'function',
      );
    }
  });

  it('FIXTURE_GENERATORS keys are unique .sb3 filenames', () => {
    const keys = Object.keys(FIXTURE_GENERATORS);
    expect(new Set(keys).size, 'duplicate fixture filenames').toBe(keys.length);
    for (const name of keys) {
      expect(name.endsWith('.sb3'), `${name} is not an .sb3 fixture`).toBe(true);
    }
  });

  it('the repo-root derivation points at the real workspace', () => {
    expect(realRoot.endsWith('TurboWasm'), `realRoot=${realRoot}`).toBe(true);
    expect(realOutDir.endsWith(join('TurboWasm', '.test-fixtures'))).toBe(true);
  });
});

describe('ensureTestFixtures: directory + write contract', () => {
  let originals: Map<string, Buffer> | null = null;

  beforeEach(async () => {
    // Snapshot the current `.test-fixtures/` so we can restore them
    // after stomping-on-by-idempotency tests. The real workspace is
    // gitignored — local-only mutation, not a remote concern.
    originals = new Map();
    if (existsSync(realOutDir)) {
      for (const name of readdirSync(realOutDir)) {
        if (name === '.gitkeep') continue;
        originals.set(name, readFileSync(join(realOutDir, name)));
      }
    }
    // Seed the workspace if it's empty (e.g. fresh-clone scenario).
    await ensureTestFixtures();
  });

  afterEach(() => {
    if (!originals) return;
    for (const [name, buf] of originals) {
      writeFileSync(join(realOutDir, name), buf);
    }
    originals = null;
  });

  it('writes every default fixture (no duplicates, no strays)', async () => {
    const result = await ensureTestFixtures();
    expect(result.outDir).toBe(realOutDir);
    expect(result.skipped).toEqual([]);
    expect(result.written.sort()).toEqual([...DEFAULT_FIXTURES].sort());
    const onDisk = readdirSync(realOutDir)
      .filter((name) => name !== '.gitkeep')
      .sort();
    expect(onDisk).toEqual([...DEFAULT_FIXTURES].sort());
    for (const name of onDisk) {
      expect(statSync(join(realOutDir, name)).size, `${name} is empty`).toBeGreaterThan(0);
      const head = readFileSync(join(realOutDir, name)).subarray(0, 2).toString('ascii');
      expect(head, `${name} is not a ZIP (PK header missing)`).toBe('PK');
    }
  });

  it('regenerates a fixture stomped with garbage (idempotent overwrite)', async () => {
    const target = 'bench-touching.sb3';
    const sb3Path = join(realOutDir, target);
    expect(existsSync(sb3Path)).toBe(true);
    writeFileSync(sb3Path, Buffer.from('garbage'));
    expect(readFileSync(sb3Path, { encoding: 'ascii' }).startsWith('garbage')).toBe(true);

    await ensureTestFixtures();

    const fresh = readFileSync(sb3Path);
    expect(fresh.subarray(0, 2).toString('ascii')).toBe('PK');
    expect(fresh.length).toBeGreaterThan(0);
  });

  it('reports unmatched names as skipped without crashing', async () => {
    const result = await ensureTestFixtures({ only: ['does-not-exist.sb3'] });
    expect(result.skipped).toEqual(['does-not-exist.sb3']);
    expect(result.written).toEqual([]);
  });

  it('honors partial `only` requests without touching other fixtures', async () => {
    const before = new Map(
      readdirSync(realOutDir)
        .filter((n) => n !== '.gitkeep')
        .map((n) => [n, readFileSync(join(realOutDir, n))]),
    );

    const result = await ensureTestFixtures({ only: ['repro.sb3'] });
    expect(result.written).toEqual(['repro.sb3']);

    // Every other fixture must be byte-identical pre/post the partial run.
    for (const [name, originalBuf] of before) {
      if (name === 'repro.sb3') continue;
      const current = readFileSync(join(realOutDir, name));
      expect(current.equals(originalBuf), `${name} was modified by a partial run`).toBe(true);
    }
  });

  it('every generator returns the expected fixture file on disk', async () => {
    // Drives each generator in isolation so a regression in one
    // fixture cannot mask the others. This is the unit-level version
    // of the registry check above.
    await ensureTestFixtures();
    for (const name of DEFAULT_FIXTURES) {
      const path = join(realOutDir, name);
      expect(existsSync(path), `${name} missing after ensureTestFixtures()`).toBe(true);
      const head = readFileSync(path).subarray(0, 2).toString('ascii');
      expect(head, `${name} is not a ZIP (PK header missing)`).toBe('PK');
    }
  });
});
